### ISSUE TITLE
Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by dgroch** [matthewmueller/x-ray#131]
I can't figure out why I'm getting this error.

per the docs, i installled x-ray with

```
npm install x-ray
```

I've tried running everything, including the sample code

```
var Xray = require('x-ray');
var x = Xray();

x('https://dribbble.com', 'li.group', [{
  title: '.dribbble-img strong',
  image: '.dribbble-img [data-src]@data-src',
}])
  .paginate('.next_page@href')
  .limit(3)
  .write('results.json')
```

But I always get a similar error

```
/Users/Daniel/node_modules/x-ray/node_modules/cheerio/lib/api/traversing.js:10
    return memo.concat(_.filter(elem.children, isTag));
                                    ^
TypeError: Cannot read property 'children' of undefined
    at /Users/Daniel/node_modules/x-ray/node_modules/cheerio/lib/api/traversing.js:10:37
    at /Users/Daniel/node_modules/x-ray/node_modules/cheerio/node_modules/lodash/lodash.js:774:11
    at /Users/Daniel/node_modules/x-ray/node_modules/cheerio/node_modules/lodash/lodash.js:3901:15
    at baseReduce (/Users/Daniel/node_modules/x-ray/node_modules/cheerio/node_modules/lodash/lodash.js:771:5)
    at Function.reduce (/Users/Daniel/node_modules/x-ray/node_modules/cheerio/node_modules/lodash/lodash.js:7811:14)
    at exports.find (/Users/Daniel/node_modules/x-ray/node_modules/cheerio/lib/api/traversing.js:9:17)
    at module.exports (/Users/Daniel/node_modules/x-ray/node_modules/cheerio/lib/cheerio.js:86:18)
    at new initialize (/Users/Daniel/node_modules/x-ray/node_modules/cheerio/lib/static.js:26:20)
    at initialize (/Users/Daniel/node_modules/x-ray/node_modules/cheerio/lib/static.js:23:14)
    at absolute (/Users/Daniel/node_modules/x-ray/lib/absolutes.js:41:14)
```

any ideas?

**Comment by OllieJennings** [comment]
@dgroch This could be due to the fact that the html structure of the page in the examples has changed since the example was created.
