### ISSUE TITLE
examples broken 

### ISSUE THREAD

**Issue by pvijeh** [matthewmueller/x-ray#173]
the examples dont work 

/Users/peter/Desktop/projects/www/web-scraper/x-ray/examples/collection-of-collections/index.js:3
var html = read(path.resovlve(__dirname, 'index.html'))
                     ^

TypeError: path.resovlve is not a function
    at Object.<anonymous> (/Users/peter/Desktop/projects/www/web-scraper/x-ray/examples/collection-of-collections/index.js:3:22)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

**Comment by vivdev** [comment]
It's the same typo in all examples: 

path.resovlve which should be path.resolve instead.

And there is one more fix needed, it should be 2 directories up in each example like below: 

var Xray = require('../..')

I could run all the examples after these changes.  I can fix this, if someone gives me the permissions to repo.

**Comment by lathropd** [comment]
Subsequently fixed by a PR.
